kind: Deployment
apiVersion: apps/v1
metadata:
  name: restful-dep
  labels:
    app: restful-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: restful-dep
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: restful-dep
    spec:
      containers:
        - name: restful
          image: bioflows/restful
      restartPolicy: Always
